spring.application.name=mail
spring.profiles.active=rabbit

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=mail
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.topic.name=mail

com.thelastimperial.mail.mq.queue=mail-queue
